CREATE TABLE proveedores (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit_empresa VARCHAR(50) NOT NULL UNIQUE,
    nombre_empresa VARCHAR(150) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    tipo_carga VARCHAR(20) NOT NULL CHECK (tipo_carga IN ('MANUAL', 'AUTOMATICO')),
    estado_registro VARCHAR(20) NOT NULL CHECK (estado_registro IN ('ACTIVO', 'INACTIVO')),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);